# GitHub Sponsors
github: [agrocryptoorg]

# Outras plataformas
patreon: agrocrypto
open_collective: agrocrypto
ko_fi: agrocrypto
tidelift: crates.io/agrocrypto-core
liberapay: agrocrypto
issuehunt: agrocryptoorg
buy_me_a_coffee: agrocrypto
thanks_dev: agrocrypto

# Custom links diretos (Bitcoin, USDC, etc.)
custom: ['https://agrocrypto.exchange/sponsor', 'https://crates.io/crates/agrocrypto-core', 'https://github.com/agrocryptoorg/agrocrypto-core']
